name: Deploy to Cafe24 Tomcat

on:
  push:
    branches:
      - main  # 배포할 브랜치 지정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/ROOT.war

          # clean-destination-dir: false  # 더 이상 사용되지 않음 (필요 없으면 제거)
      - name: Shutdown and Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: gdbmsdev.cafe24.com
          port: 21
          username: gdbmsdev
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo /tomcat/bin/shutdown.bat  # 톰캣 종료
            sleep 6  # 6초 대기
            sudo /tomcat/bin/startup.bat  # 톰캣 시작