name: Deploy to Cafe24 Tomcat

on:
  push:
    branches:
      - main  # 배포할 브랜치 지정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/ROOT.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: gdbmsdev.cafe24.com
          port: 21
          username: gdbmsdev
          password: ${{ secrets.SSH_PASSWORD }}
          server-dir: /tomcat/webapps-javaee/
      - name: Shutdown and Restart Tomcat
      uses: appleboy/ssh-action@master
      with:
        host: gdbmsdev.cafe24.com
        port: 21
        username: gdbmsdev
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo /gdbmsdev/tomcat/bin/shutdown.bat  # 톰캣 종료
          sleep 6  # 6초 대기
          sudo /gdbmsdev/tomcat/bin/startup.bat  # 톰캣 시작
