name: Deploy to Tomcat

on:
  push:
    branches:
      - main  # 배포할 브랜치 지정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 사용하는 JDK 버전에 맞게 수정
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build/libs  # Gradle 빌드 결과물 디렉토리
      - name: Deploy to Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: gdbmsdev.cafe24.com
          port: 21
          username: gdbmsdev
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo service tomcat stop
            sudo rm -rf /usr/local/tomcat/webapps/ROOT  # 기존 ROOT 디렉토리 삭제
            sudo rm -rf /usr/local/tomcat/webapps/ROOT.war  # 기존 ROOT.war 파일 삭제
            sudo unzip -qq build/libs/*.war -d /usr/local/tomcat/webapps/ROOT  # ROOT 디렉토리에 압축 해제
            sudo service tomcat start
